website/blog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit = SubmitField("Post")

website/blog/blog_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from website import db
from website.blog.models import BlogPost
from website.blog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)


# Create
# blog poat viewing
# updating
# delete


@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    form = BlogPostForm()
    if form.validate_on_submit():

        blog_post.title = form.title.data

        blog_post.text = form.text.data
        db.session.commit()
        flash("Blog post updated")
        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post_id))

    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template("create_post.html", title="Updating", form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash("Blog post Deleted")

    return redirect(url_for("core.index"))


@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(
            title=form.title.data, text=form.text.data, user_id=current_user.id
        )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog post created")
        return redirect(url_for("core.index"))

    return render_template("create_post.html", form=form)


@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template(
        "blog_post.html", title=blog_post.title, date=blog_post.date, post=blog_post
    )

website/blog/core/views.py
from flask import render_template, request, Blueprint
from website.blog.models import BlogPost

core = Blueprint("core", __name__)


@core.route("/blog/")
def index():
    page = request.args.get("page", 1, type=int)
    blog_post = BlogPost.query.order_by(BlogPost.date.desc()).paginate(
        page=page, per_page=5
    )
    return render_template("index.html", blog_post=blog_post)


@core.route("/blog/info")
def info():
    return render_template("info.html")

website/blog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from website import db
from website.blog.models import User, BlogPost
from website.blog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from website.blog.users.picture_handler import add_profile_pic
import random 
import os

users = Blueprint("users", __name__)

# Register
# login_user
# logout ##
# Account
# users list of blog post
@users.route("/blog/<username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_post = (
        BlogPost.query.filter_by(author=user)
        .order_by(BlogPost.date.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_blog_posts.html", blog_posts=blog_post, user=user)


@users.route("/blog/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("User ACccount Updated")
        return redirect(url_for("users.account"))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for(
        "static", filename="profile_pics/" + current_user.profile_image
    )
    return render_template("account.html", profile_image=profile_image, form=form)


@users.route("/blog/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login in success")

            next = request.args.get("next")

            if next == None or not next[0] == "/":
                next = url_for("core.index")

            return redirect(next)

    return render_template("login.html", form=form)


@users.route("/blog/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            username=form.username.data,
            password=form.password.data,
            image=pick_random_image()


        )

        db.session.add(user)
        db.session.commit()

        flash("Thanks for registration")

        return redirect(url_for("users.login"))
    return render_template("register.html", form=form)


@users.route("/blog/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


def pick_random_image():

       
    dirname = os.path.dirname(__file__)
    website = os.path.join(dirname, "..","..")
    path_robots = os.path.join(website,"static" ,"robots")
    files=os.listdir(path_robots)
    choice=random.choice(files)
    return choice

website/core_app/views.py
# website/core/views
from flask import render_template, Blueprint

core_app = Blueprint("core_app", __name__)


@core_app.route("/")
def home():
    return render_template("home.html")


@core_app.route("/about")
def about():
    return render_template("about.html")


@core_app.route("/contact")
def contact():
    return render_template("contact.html")

website/fakenews_app/views.py
#! /usr/bin/python3
from website.fakenews_app.functions import text_process
from flask import Flask, render_template, session, redirect, url_for, Blueprint
from flask_wtf import FlaskForm
from website.fakenews_app.forms import NewsForm
import joblib, string, os
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords


news = Blueprint("news", __name__)


@news.route("/news_form", methods=("POST", "GET"))
def news_app():

    form = NewsForm()
    full_path = os.path.join("website//static//", "news_classifier.joblib")

    model = joblib.load(full_path)
    y = False  # set flag yto false

    if form.validate_on_submit():
        news = [(form.text.data)]
        y = str(model.predict(news)[0])

        session["y"] = str(model.predict(news)[0])
        session["proba_fake"] = str(model.predict_proba(news)[0][0].round(3))
        session["proba_real"] = str(model.predict_proba(news)[0][1].round(3))

        if y == "1":
            session["y"] = "  Real"
        elif y == "0":
            session["y"] = "  Fake"
        else:
            session["y"] = "Sorry we could not get an answer for you. Please try again"

        # return redirect(url_for("news.news_prediction"))

    return render_template("news_form.html", form=form, y=y)


@news.route("/news_prediction")
def news_prediction():
    return render_template("news_prediction.html")

website/templates/account.html
{%extends "baseb.html"%}

{%block content%}
<div class="myjumbo pt-5">
  <div align="center">
    <h1>Welcome to your home page <span class="account-name-of-user">{{current_user.username}}</span></h1>

    <img src="{{url_for("static",filename="profile_pics/"+current_user.profile_image)}}" alt="Userprofile pic">


  </div>

</div>

<div class="container">

  <div class="account-form">



    <form method="POST" action="" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.username.label(class="d-block ")}} {{form.username(class="d-block")}}
      </div>
      <div class="form-group">
        {{form.email.label(class="d-block")}} {{form.email(class="d-block")}}
      </div>
      <div class="form-group">

        {{form.picture.label(class="d-block")}} {{form.picture(class="d-block")}}

        <br>
        {{form.submit(class="d-block btn btn-primary")}}

      </div>

    </form>
  </div>

</div>
{%endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8" name="viewport" content="width=device-width, user-scalable=no">

  <!-- title -->
  <title>Takuonline</title>
  
    <!-- Static files -->
  <link rel="stylesheet" href="/static/style.css">
 
  <!-- google fonts -->
  
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">

  <!-- favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="../static/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="../static/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="../static/favicon/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">

  <!-- bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
    integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous">
  </script>
</head>


<body>
<!-- collapsing nav bar -->
  <div class="c-nav">
      <input type="checkbox" class="c-nav__checkbox" id="navi-toggle">
      <label for="navi-toggle"  class="c-nav__button">
          <span class="c-nav__icon">&nbsp;</span>
      </label>
      <div class="c-nav__background">&nbsp;</div>
      <nav class="c-nav__nav">
          <ul class="c-nav__list">
              <li class="c-nav__item"><a href="{{url_for("core_app.home")}}"" class="c-nav__link"><span>01</span> Home</a></li>
              <li class="c-nav__item"><a href="#about" class="c-nav__link"><span>02</span>About Me</a></li>
              <li class="c-nav__item"><a href="{{url_for("core.index")}}" class="c-nav__link"><span>03</span> My blog</a></li>
              <li class="c-nav__item"><a href="{{url_for("core_app.contact")}}" class="c-nav__link"><span>04</span> Contact</a></li>
              <!-- <li class="c-nav__item"><a href="#" class="c-nav__link"><span>05</span> Book now</a></li> -->
          </ul>
      </nav>
  </div>

  <script>
    document.querySelectorAll(".c-nav__link")[0].addEventListener("click",function (){

      document.getElementById("navi-toggle").checked = false;
      })
      document.querySelectorAll(".c-nav__link")[1].addEventListener("click",function (){
      
      document.getElementById("navi-toggle").checked = false;
      })
      
      document.querySelectorAll(".c-nav__link")[2].addEventListener("click",function (){
      
      document.getElementById("navi-toggle").checked = false;
      })
  </script>


  <nav class="mynavbar">
    <!-- <a class="#" href="{{url_for("core_app.home")}}"> <img class="logo" src="../static/logo/logo.png" alt="Logo"></a> -->
    <a class="logo" href="{{url_for("core_app.home")}}">Taku-online</a>  
   
    <ul class="mynavbar__list">
      
      
      <li>
        <a class="mynavbar__list-navbar-item navbar-item--1" href="{{url_for("core_app.home")}}">Home</a>
      </li>
      <li>
        <a class="mynavbar__list-navbar-item navbar-item--2" href="#about">About Me</a>
      </li>
      <li>
        <a class="mynavbar__list-navbar-item navbar-item--3" href="{{url_for("core_app.contact")}}">Contact</a>
      </li>
      <li>
        <a class=" nav-myblog" href="{{url_for("core.index")}}">My blog</a>
      </li>
    </ul>
  </nav>

  {%block content%}

  {% endblock %}


</body>

</html>

website/templates/baseb.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8" name="viewport" content="width=device-width, user-scalable=no">


  <!-- font link -->
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">


  <!-- boot strap files -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

  <!-- css file -->
  <link rel="stylesheet" href="../static/blog_css.css">

  <title>Taku's Blog</title>


</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-transparent my-3 pt-5 justify-content-end">
    <a class="navbar-brand pl-5 pt-4 text-success h1 mt-4 logo" href="{{url_for('core_app.home')}}">Taku</a>
    <button class="navbar-toggler bg-dark ml-auto mb-2 mr-4 collapsed" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse flex-grow-0 collapse" id="navbarSupportedContent">
      <ul class="navbar-nav text-right ml-auto">
        <li class="nav-item active">
          <div class="blog-nav">

            <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
        </li>

        <!-- <li class="nav_link "> <a href="{{url_for('core_app.home')}}">Home</a> </li> -->

        <!-- <div class="my-nav-items"> -->
        <li class="nav_link my-nav-items text-light my-2 text-decoration-none"> <a class="nav-hover px-4 py-2"
            href="{{url_for('core.index')}}">Blog home</a> </li>

        <!-- <li class=" my-nav-items my-nav-items text-light text-decoration-none"> <a href="{{url_for('core.info')}}">About</a> </li> -->
        {%if current_user.is_authenticated%}
        <li class="nav_link my-nav-items my-2 text-light"> <a class="nav-hover px-4 py-2"
            href="{{url_for('users.logout')}}">Logout</a> </li>
        <li class="nav_link my-nav-items my-2 text-light"> <a class="nav-hover px-4 py-2"
            href="{{url_for('users.account')}}">Account</a> </li>
        <li class="nav_link my-2 text-light "> <a class="nav-hover" href="{{url_for('blog_posts.create_post')}}"><span
              class="btn btn-success ">Create Post</span></a> </li>
        {%else%}
        <li class="nav_link my-2 text-light my-nav-items"> <a class="nav-hover px-4 py-2"
            href="{{url_for('users.login')}}">login</a> </li>
        <li class="nav_link my-2 text-light my-nav-items"> <a class="nav-hover px-4 py-2"
            href="{{url_for('users.register')}}">Register</a> </li>
        {%endif%}
        <li class="nav_link my-nav-items ml-4 text-light my-2  mr-1 text-decoration-none"> <a
            class="py-2 px-4 home-btn btn-warning" href="{{url_for('core_app.home')}}">Home <span
              class="sr-only">(current)</span></a> </li>

    </div>
    </div>

    <!-- <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li> -->
    <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->

    <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->

    </ul>

    <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
    </div>
  </nav>

  <!-- <ul class="blog-nav">
  <li class="nav_link "> <a href="{{url_for('core_app.home')}}">Home</a> </li>
  <li class="nav_link "> <a href="{{url_for('core.index')}}">Blog home</a> </li>

  <li class="nav_link"> <a href="{{url_for('core.info')}}">About</a> </li>
  {%if current_user.is_authenticated%}
  <li class="nav_link"> <a href="{{url_for('users.logout')}}">Logout</a> </li>
  <li class="nav_link"> <a href="{{url_for('users.account')}}">Account</a> </li>
  <li class="nav_link"> <a href="{{url_for('blog_posts.create_post')}}">Create Post</a> </li>
  {%else%}
  <li class="nav_link"> <a href="{{url_for('users.login')}}">login</a> </li>
  <li class="nav_link"> <a href="{{url_for('users.register')}}">Register</a> </li>
  {%endif%}
</ul> -->



  <div class="container my-bg">
    {%block content%}

    {%endblock%}
  </div>
</body>

</html>

website/templates/blog_post.html
{%extends "baseb.html"%}

{%block content%}
<div class="blog-post myjumbo">
  
  <div class="pic-and-pro">
    <img class="user-post-pic img-fluid img-thumbnail"
      src="{{url_for("static",filename="profile_pics/"+post.author.profile_image)}}" alt="Userprofile pic">
    <div class="user-post-profile">
      <h1 class="display-4 user-post-header">{{post.title}}</h1>
      <div class="user-post-text">
        <h2 class="lead">Written by: {{post.author.username}}</h2>
        <h6>Published: {{post.date.strftime("%B %d, %Y")}}</h6>
      </div>
    </div>
  </div>

</div>
{% if post.author ==  current_user%}
<div class="update-post">
  <button class="btn btn-warning"> <a href="{{url_for("blog_posts.update",blog_post_id=post.id)}}">Update</a></button>

  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
</div>
{%endif%}
<p class="blog-text " style="white-space: pre-wrap;">{{post.text}}</p>



<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>


      </div>



      {%endblock%}

website/templates/contact.html
{%extends"base.html" %}
{%block content%}
<div class="contact-page">


  <div class="contact-container">
    <h1 class="display-4 text-success">Contact</h1>
    <br>
    
    <hr>
    <br>
    <br>
    <h3>You can contact me on the following channels.</h3>
    <br>
    <br>
    <br>
    
<div class="contact">
    

   
      <div class="contact__item ">
        <a href="https://www.facebook.com/takudzwa.makusha.3"> <img src="static/contact_images/fb.png" alt=""> </a>
      </div>
      <div class="contact__item ">
        <a href="https://www.instagram.com/takuonline3/"> <img src="static/contact_images/insta.png" alt=""> </a>
      </div>
    


      <div class="contact__item ">
        <a href="whatsapp://send?text=Hello, l just visited your site!&phone=+27676522180"> <img src="static/contact_images/whatsapp.png"
            alt=""> </a>
      </div>
      <div class="contact__item ">
        <a href="https://twitter.com/takuonline"> <img src="static/contact_images/twitter.png" alt=""> </a>
      </div>
  
    </div>
 


 

</div>
<div class="contact-footer">
  <div class="contact-footer__text">
    <a href="https://www.freepik.com/free-photos-vectors/logo">Logo vector created by freepik - www.freepik.com</a>
    <p>Email me at: tbmakusha@gmail.com</p>
  </div>
</div>


{%endblock%}

website/templates/index.html
{%extends "baseb.html"%}

{%block content%}


<div class="myjumbo">
  <h1 class="text-center jumbo-display-4 display-4 jumbo-text">Taku's Blog</h1>
  <hr class="my-4 w-75">
  <p class=" text-center lead jumbo-text">This is my second website built on the Python flask.
     Why dont you give it a try.
  
    <ol class="list-instructions">
      <li>Login / register</li>
      <li>Make a post</li>
    </ol>
  
  </p>

    

</div>

<div class="blog-div">

  {% for post in blog_post.items %}
  <div class="mycard">

    <!-- <div class="card bg-info" > -->

    <div class="card-body">
      <h2><a class="card-title"
          href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
      <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By:
        {{ post.author.username }}</a>
      <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
      <p class="card-text">{{ post.text[:100] }}...</p>
      <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
    </div>
    <!-- </div> -->
  </div>

  {% endfor %}
  <div class="pagination justify-content-center">


    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in blog_post.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_post.page == page_num %}
        <li class="page-item disabled">
          <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>

        {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </nav>
  </div>

</div>
{%endblock%}

website/templates/news_form.html
{%extends "base.html"%}
{%block content%}



<div class="container form-container">


  <h1 style="color: #28a745;" text-success>Real/Fake news Classifier.</h1>
  <br>
  <form method="post">

    {{form.hidden_tag()}}
    {{form.text.label}}
    <br>
    {{form.text(class="form-group w-75 h-25", rows="7" )}}

    <br>
    {{form.submit(class_="btn btn-primary",href="#news-results")}}
  </form>


  <div class="newsapp-form">
    <h1 class="display-4 text-success text-center">News prediction Results </h1>
    {% if form.validate_on_submit() %}


    <h3 class="text-center ">Thank you for your submission</h3>
    <hr class="w-75">

    <div class="newsapp-form__result" id="news-results"> The model predicts the News article is <span
        class=" badge-info">{{session['y']}}</span>
    </div>

    <!-- The following is the probability results of your article -->

    <!-- <h3>Probability of Fake news:  {{session['proba_fake']}}</h3> -->

    <!-- <h3>Probability of Real news:  {{session['proba_real']}} </h3> -->
    <!-- <h1> {{session['proba']}}</h1> -->
    <!-- <br> -->
    <!-- <a href="{{url_for('news.news_app')}}"> Do you want to try again </a> -->
    <!-- </div> -->


  </div>
  <!-- <br> -->
  <ul>
    <li>Please be advised that l do not guarantee the accuracy of this application to be a perfect. and will not take
      any
      responsibility for a misclassification. </li>
    <li>
      This app was trained on a actual news articles and was able to reach an
      accuracy of more than 80%
    </li>
  </ul>
  {%endif%}
</div>



{% endblock %}

website/templates/user_blog_posts.html
{%extends "baseb.html"%}

{%block content%}
<div class="container">
  <div class="jumbotron">
    <div align="center">

      <h1>Welcome to the page for {{user.username}}</h1>
      <img src="{{url_for("static",filename="profile_pics/+user.profile_image")}}" alt="">

    </div>

  </div>

{%for post in blog_posts.items  %}
<h2><a href="{{url_for("blog_posts.blog_post",blog_post_id=post.id)}}"> {{post.title}}  </a></h2>
Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
<p class="text-muted" >Published on {{post.date.strftime("%Y-%m-%d")}} </p>
<br>
<p>{{post.text}}</p>
<br>

{%endfor%}
</div>

<nav aria-label="Page Navigation example">
  <ul  class="pagination justify-content-center"  >
    {%for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
    {%if blog_posts.page == page_num%}
    <li class="page-item disabled">
      <a class="page-link" href="{{url_for("users.user_posts",username=user.username,page=page_num)}}>{{page_num}}</a>
    </li>
{%else%}
<li class="page-item ">
  <a class="page-link" href="{{url_for("users.user_posts",username=user.username,page=page_num)}}>{{page_num}}</a>
</li>
{%endif%}
    {%endfor%}
  </ul>

</nav>

{%endblock%}